# Generated by Django 3.2 on 2023-07-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('-created',), 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='command_response',
            field=models.TextField(choices=[('Я бот который родился в процессе написания тестового задания. Расскажу интересные новости и скажу какая погода. Cписок рабочих команд ты увидешь заюзая команду: /help Надеюсь тебе понравится))', 'START'), ('/start: Скажу привет и расскажу кратко, что умею, \n/help: Расскажу какими командами ты можешь воспользоваться, \n/weather: расскажу какая погода в этом городе, \n/news: Интересные новости читать будем??!!1! ', 'HELP'), ('Я ща тебе такое расскажу, только сначала присядь ', 'NEWS'), ('Так а ты вообще знаешь че там по погоде? Ща буду рассказывать ', 'WEATHER')], verbose_name='Команда для бота'),
        ),
    ]
