# Generated by Django 3.2 on 2023-07-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='command_response',
            field=models.TextField(choices=[('Я бот который родился в процессе написания тестового задания. Расскажу интересные новости и скажу какая погода. Cписок рабочих команд ты увидешь заюзая команду: /help Надеюсь тебе понравится))', 'старт'), ('/start: Скажу привет и расскажу кратко, что умею, \n/help: Расскажу подробно какими командами ты можешь воспользоваться, \n/weather: расскажу какая погода в этом городе, \n/news: Интересные новости читать будем??!!1! ', 'хелпа'), ('Я ща тебе такое расскажу, только сначала присядь ', 'новости'), ('Такс а ты вообще знаешь че там по погоде? Ща буду рассказывать ', 'погода')], verbose_name='Команда для бота'),
        ),
    ]
