# Generated by Django 3.2 on 2023-07-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20230726_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='message/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на новость'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок'),
        ),
    ]
