# Generated by Django 3.2 on 2023-07-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20230726_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Влажность воздуха'),
        ),
    ]
